### PR TITLE
fix(PrefixSource): consistent empty line handling

### LINKED ISSUE #8: PrefixSource bug: source() !== sourceAndMap().source
empty lines are not handled consistently which breaks `ReplaceSource` indices that might be based on a particular version of the source.

**Example**
Prefix: `foobar `
Nodes: `["console.log(1);\n", "\n", "console.log(2);\n"]`

source() -> `foobar console.log(1);\n\nfoobar console.log(2);\n`
sourceAndMap().source -> `foobar console.log(1);\nfoobar \nfoobar console.log(2);\n`

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #8

### CODE REVIEW

**Comment by bebraw** [comment]
Can you sign the CLA? Thanks.

**Comment by patrickhulce** [comment]
Hey @bebraw just an update here, I'd be happy to, but I'm currently waiting on Google's Open Source Programs Office for the greenlight. Trying to work with them to get it whitelisted for any other folks that want to contribute in the future as well 😄

**Comment by TheLarkInn** [comment]
If it helps we can point them towards the http://js.foundation where all the legal information is aggregated.

**Comment by patrickhulce** [comment]
Sorry for the delay but I've signed and it should now be on our internal whitelist for the future!

**Comment by patrickhulce** [comment]
hang on, I found a test case where this breaks. might be better to approach from the source side than the sourceAndMap side as the node logic is confusing enough already

**Comment by bebraw** [comment]
@TheLarkInn Merge + publish as you have time.

**Comment by TheLarkInn** [comment]
Thank you very much!

**Pull request merged**
