### PR TITLE
replace source-map with source-map-sync

### PR DESCRIPTION
**Pull request by 7rulnik**

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
What is different with `source-map-js`?

**Comment by 7rulnik** [comment]
@alexander-akait it's the original source-map with WASM, but with sync API. It's should be 2x faster than source-map-js. I will make a PR to source-map that easily to review.

**Comment by alexander-akait** [comment]
Do you have repo?

**Comment by 7rulnik** [comment]
@alexander-akait https://github.com/7rulnik/source-map-sync/pull/1

**Comment by alexander-akait** [comment]
Some developers bundle webpack, it is rare case, but it can be breaking change for them

**Comment by 7rulnik** [comment]
Yeah, I think that I can transform WASM into base64 so it will be not a problem

**Comment by 7rulnik** [comment]
@alexander-akait should be bundleable now :)

**Comment by 7rulnik** [comment]
https://github.com/webpack/webpack-sources/issues/34#issuecomment-887332263

**Pull request closed without merging**
