### PR TITLE
Improvements on OriginalSource and ReplaceSource

### PR DESCRIPTION
**Pull request by jevancc**
**OriginalSource**
Use `str.match(regexp)` in `_splitCode`, which is faster than string traversal with for loop

**RepalceSource**
Make `ReplacementEnumerator` take the replacements in descending order and remove redundant code.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@jevancc please accept CLA

**Comment by evilebottnawi** [comment]
@jevancc looks we need more tests

**Comment by jevancc** [comment]
@evilebottnawi you mean tests for OriginalSource?

**Comment by evilebottnawi** [comment]
@jevancc tests on you code, you can see above what coverage decrease

**Comment by jevancc** [comment]
@evilebottnawi it should be fine now. The small decrease in test coverage is because of the removing of redundant code which was previously hit in the test.

**Comment by evilebottnawi** [comment]
@jevancc thanks in near future we will review this

**Comment by ooflorent** [comment]
> which is faster than string traversal with for loop

Can you create a gist with a benchmark please?

Why did you change the iteration order? I found the proposed solution harder to understand. Could you elaborate a bit more the motiviation?

**Comment by jevancc** [comment]
@ooflorent 
> Can you create a gist with a benchmark please?
* Node.js version: 10.8.0

|  String length | Portion of Splitter |**Old split** | **New split** |
|----------------|---------------------|--------------|---------------|
| 1,000,000 | 30% | 49.42ms | 49.07ms |
| 1,000,000 | 20% | 38.33ms | 36.21ms |
| 1,000,000 | 10% | 21.83ms | 18.40ms |
| 1,000,000 |  5% | 13.76ms | 7.41ms |

More details: [Benchmark gist](https://gist.github.com/jevancc/bfd43a613f350b46d0b2b48334089584)

> I found the proposed solution harder to understand. Could you elaborate a bit more the motiviation?

My motivation is very simple: other functions in `ReplaceSource` (`.source()`, `.listMap()`) all take the replacements in descending order and use the same sorting method `._sortReplacements()`.

Since this change is not that complicated, it is better not to maintain another sorting function and re-sort the replacements in different order everytime when calling `.node()`.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
